services:
  - type: web
    name: GP
    env: python 3.12
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn API.app:app
    envVars:
      - key: FLASK_ENV
        value: production
